# Pyspark

## Dataset

In [1]:
from sklearn.datasets import fetch_california_housing

california_housing = fetch_california_housing(as_frame=True)
california_housing_csv = california_housing["data"]
california_housing_csv.to_csv("data/housing.csv", index = False)

## Pandas Version

In [2]:
import pandas as pd 
data_pandas = pd.read_csv("data/housing.csv")
data_pandas

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

### Aggregate Function

In [13]:
data_pandas.groupby(["HouseAge"]).sum().head(20)

,MedInc,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
HouseAge,,,,,,,
1.0,16.0136,36.352363,6.208422,1314.0,12.976350,144.82,-477.83
2.0,299.7304,443.647060,73.863799,120817.0,159.372502,2058.68,-6909.04
3.0,338.5360,424.811934,73.934135,186110.0,169.551917,2187.64,-7374.06
4.0,989.5086,1167.508603,213.192367,537314.0,532.152350,6678.69,-22693.53
5.0,1146.2232,1455.023412,275.235401,603017.0,800.102313,8597.16,-29016.00
6.0,701.3428,933.159425,176.934290,346502.0,461.785257,5637.30,-19039.09
7.0,781.2799,1091.400811,200.395719,457289.0,513.965892,6220.25,-20844.51
8.0,918.6237,1293.779173,242.070510,415781.0,692.312897,7363.23,-24579.97
9.0,884.8672,1232.894073,234.632055,386830.0,594.419328,7315.09,-24457.61
10.0,1069.3342,1596.568521,315.614596,452212.0,753.122942,9481.46,-31521.73
11.0,998.8787,1597.252641,316.269427,505436.0,744.845160,9117.60,-30349.14
12.0,949.2420,1372.515930,267.266769,506848.0,690.744278,8504.19,-28404.41
13.0,1253.5640,1880.140388,362.147158,536457.0,868.294020,10816.86,-36052.99
14.0,1695.6028,2513.959431,484.343375,765142.0,1183.165822,14821.81,-49254.18
15.0,2079.9001,3042.664079,585.011213,830622.0,1446.362744,18381.02,-61182.52
16.0,3310.6721,4629.130034,872.410774,1143822.0,2248.878775,27549.57,-92178.90
17.0,2747.2069,4103.913788,815.356455,1120882.0,1967.667556,25103.60,-83502.19
18.0,2267.0861,3253.854924,640.739179,916939.0,1650.596886,20488.63,-68213.04
19.0,1887.7152,2827.383880,571.728948,812882.0,1435.759238,17985.10,-60003.12
20.0,1757.0574,2541.894691,517.168259,718697.0,1331.673793,16806.56,-55749.70

## Spark Version

In [4]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('Agg').getOrCreate()

In [9]:
data_spark = spark.read.csv("data/housing.csv", header=True, inferSchema=True)
data_spark.show()

+------+--------+------------------+------------------+----------+------------------+--------+---------+
|MedInc|HouseAge|          AveRooms|         AveBedrms|Population|          AveOccup|Latitude|Longitude|
+------+--------+------------------+------------------+----------+------------------+--------+---------+
|8.3252|    41.0| 6.984126984126984|1.0238095238095237|     322.0|2.5555555555555554|   37.88|  -122.23|
|8.3014|    21.0| 6.238137082601054|0.9718804920913884|    2401.0| 2.109841827768014|   37.86|  -122.22|
|7.2574|    52.0| 8.288135593220339| 1.073446327683616|     496.0|2.8022598870056497|   37.85|  -122.24|
|5.6431|    52.0|5.8173515981735155|1.0730593607305936|     558.0| 2.547945205479452|   37.85|  -122.25|
|3.8462|    52.0| 6.281853281853282|1.0810810810810811|     565.0|2.1814671814671813|   37.85|  -122.25|
|4.0368|    52.0| 4.761658031088083|1.1036269430051813|     413.0| 2.139896373056995|   37.85|  -122.25|
|3.6591|    52.0|4.9319066147859925|0.9513618677042801|    1094.0|2.1284046692607004|   37.84|  -122.25|
|  3.12|    52.0| 4.797527047913447| 1.061823802163833|    1157.0|1.7882534775888717|   37.84|  -122.25|
|2.0804|    42.0| 4.294117647058823|1.1176470588235294|    1206.0| 2.026890756302521|   37.84|  -122.26|
|3.6912|    52.0| 4.970588235294118|0.9901960784313726|    1551.0| 2.172268907563025|   37.84|  -122.25|
|3.2031|    52.0| 5.477611940298507|1.0796019900497513|     910.0| 2.263681592039801|   37.85|  -122.26|
|3.2705|    52.0| 4.772479564032698|1.0245231607629428|    1504.0|2.0490463215258856|   37.85|  -122.26|
| 3.075|    52.0| 5.322649572649572|1.0128205128205128|    1098.0|2.3461538461538463|   37.85|  -122.26|
|2.6736|    52.0|               4.0|1.0977011494252873|     345.0|1.9827586206896552|   37.84|  -122.26|
|1.9167|    52.0| 4.262903225806451|1.0096774193548388|    1212.0|1.9548387096774194|   37.85|  -122.26|
| 2.125|    50.0| 4.242424242424242| 1.071969696969697|     697.0| 2.640151515151515|   37.85|  -122.26|
| 2.775|    52.0|5.9395770392749245|1.0483383685800605|     793.0| 2.395770392749245|   37.85|  -122.27|
|2.1202|    52.0| 4.052805280528053| 0.966996699669967|     648.0|2.1386138613861387|   37.85|  -122.27|
|1.9911|    50.0| 5.343675417661098|1.0859188544152745|     990.0|2.3627684964200477|   37.84|  -122.26|
|2.6033|    52.0| 5.465454545454546|1.0836363636363637|     690.0|2.5090909090909093|   37.84|  -122.27|
+------+--------+------------------+------------------+----------+------------------+--------+---------+
only showing top 20 rows

### Aggregate Function

In [14]:
grouped = data_spark.groupBy('HouseAge').sum()
grouped.show()

+--------+------------------+-------------+------------------+------------------+---------------+------------------+------------------+-------------------+
|HouseAge|       sum(MedInc)|sum(HouseAge)|     sum(AveRooms)|    sum(AveBedrms)|sum(Population)|     sum(AveOccup)|     sum(Latitude)|     sum(Longitude)|
+--------+------------------+-------------+------------------+------------------+---------------+------------------+------------------+-------------------+
|     8.0| 918.6236999999999|       1648.0|1293.7791726272808|242.07050979855802|       415781.0| 692.3128971076675|           7363.23|-24579.969999999972|
|     7.0| 781.2799000000001|       1225.0|1091.4008105186736|200.39571939232053|       457289.0| 513.9658917400823|           6220.25|-20844.510000000006|
|    49.0| 475.7662999999998|       6566.0| 665.5445193661707|139.76969351787423|       132552.0| 364.6753501035802|4826.0199999999995|-16116.939999999995|
|    29.0|1650.5204000000012|      13369.0|  2404.31928230994|501.88663036578583|       670398.0| 1379.123504189475| 16367.05000000002| -55065.63999999998|
|    47.0|          651.6012|       9306.0| 973.5598370568655|210.28521037117997|       209883.0| 581.3297410968942| 7083.959999999997|-23745.660000000003|
|    42.0|1262.7240000000004|      15456.0| 1753.270678789069| 384.1059448721443|       417648.0|1124.9469808261822|          13007.33|          -43968.84|
|    44.0|1247.1104999999998|      15664.0|1800.3532766976496| 379.9803606488702|       367075.0|1028.6734413591205|12576.379999999996| -42547.75999999999|
|    35.0|3224.4004999999984|      28840.0| 4286.298151091746| 856.2528258219053|       992448.0|2593.3521432121524| 28980.67999999998| -98266.38000000008|
|    18.0|2267.0860999999973|      10260.0|3253.8549243945954| 640.7391785608264|       916939.0|1650.5968862296043|          20488.63|          -68213.04|
|    39.0| 1268.506199999999|      14391.0|1797.7813245667128| 388.5932468677489|       428133.0|1110.0713209258624|13104.969999999987| -44144.21000000001|
|     1.0|           16.0136|          4.0|  36.3523631840796| 6.208422174840085|         1314.0|12.976350390902631|            144.82|            -477.83|
|    37.0|2012.4288999999997|      19869.0|2738.4375495766612| 566.5294373773969|       580008.0|1630.0757483774437| 18976.75000000001|          -64141.49|
|    34.0|2745.5980000000013|      23426.0|3764.2878878287565| 757.7797966630716|       849630.0| 2100.819356125201|24228.319999999996| -82129.02999999987|
|    25.0| 2331.883999999999|      14150.0| 3136.961079981946| 623.7583113300042|       871352.0|  1628.05372126736|20095.110000000022| -67601.16999999997|
|    36.0| 3392.795900000007|      31032.0| 4527.406826193406| 898.7825764699916|       942467.0| 3263.854226840958|30318.660000000047|-102813.47999999976|
|    41.0|  938.336999999999|      12136.0|1395.0525306035313|311.88447639994956|       307853.0|  917.817751925092|10462.109999999997| -35351.07000000003|
|     4.0| 989.5086000000002|        764.0|1167.5086033222237| 213.1923671207378|       537314.0| 532.1523496826273| 6678.689999999994|-22693.529999999995|
|    23.0| 1769.387200000001|      10304.0|2501.6858899410317| 498.8520422808539|       696320.0| 1315.238016117262|16008.069999999998| -53592.00000000002|
|    50.0|468.42329999999987|       6800.0| 672.2430168842066|145.91439954047328|       135861.0| 377.7754765208037|4894.2699999999995|-16336.809999999989|
|    45.0|1077.6397999999995|      13230.0| 1463.132016920466|305.06904154924365|       304385.0|2090.8029703449492| 10435.30999999999|-35182.959999999985|
+--------+------------------+-------------+------------------+------------------+---------------+------------------+------------------+-------------------+
only showing top 20 rows

In [16]:
spark.stop()